// quizz-app-solid/src/routes/quiz.tsx
import { useNavigate, useSearchParams } from "@solidjs/router";
import { For, Show, createEffect, createSignal } from "solid-js";
import { decodeHtml } from "../utils/decodeHtml";

interface Question {
	question: string;
	correct_answer: string;
	incorrect_answers: string[];
}

export default function Quiz() {
	const [params] = useSearchParams();
	const navigate = useNavigate();

	const [questions, setQuestions] = createSignal<Question[]>([]);
	const [current, setCurrent] = createSignal(0);
	const [loading, setLoading] = createSignal(true);
	const [selected, setSelected] = createSignal<string | null>(null);
	const [answered, setAnswered] = createSignal(false);
	const [score, setScore] = createSignal(0);
	const [shuffledAnswers, setShuffledAnswers] = createSignal<string[]>([]);
	const [hiddenAnswers, setHiddenAnswers] = createSignal<string[]>([]);
	const [hintUsed, setHintUsed] = createSignal(false); // 💡 per-question flag

	const amount = Number(params.amount || 10);
	const category = params.category;
	const isRandom = params.random === "true";

	createEffect(() => {
		const fetchQuestions = async () => {
			setLoading(true);
			const catQuery = isRandom ? "" : `&category=${category}`;
			const url = `https://opentdb.com/api.php?amount=${amount}&type=multiple${catQuery}`;
			const res = await fetch(url);
			const data = await res.json();
			setQuestions(data.results);
			setLoading(false);

			const firstQ = data.results[0];
			const shuffled = [
				...firstQ.incorrect_answers,
				firstQ.correct_answer,
			].sort(() => Math.random() - 0.5);
			setShuffledAnswers(shuffled);
			setHiddenAnswers([]);
			setHintUsed(false);
		};
		fetchQuestions();
	});

	const q = () => questions()[current()];

	createEffect(() => {
		if (!loading() && q()) {
			const answers = [...q().incorrect_answers, q().correct_answer].sort(
				() => Math.random() - 0.5,
			);
			setShuffledAnswers(answers);
			setHiddenAnswers([]);
			setHintUsed(false); // Reset on question change
		}
	});

	const handleSelect = (answer: string) => {
		if (!answered()) {
			setSelected(answer);
			setAnswered(true);
			if (answer === q().correct_answer) {
				setScore(score() + 1);
			}
		}
	};

	const nextQuestion = () => {
		const nextIndex = current() + 1;
		setSelected(null);
		setAnswered(false);

		if (nextIndex >= questions().length) {
			navigate(`/score?score=${score()}&total=${questions().length}`);
		} else {
			setCurrent(nextIndex);
			const nextQ = questions()[nextIndex];
			const shuffled = [...nextQ.incorrect_answers, nextQ.correct_answer].sort(
				() => Math.random() - 0.5,
			);
			setShuffledAnswers(shuffled);
			setHiddenAnswers([]);
			setHintUsed(false);
		}
	};

	const useHint = () => {
		if (hintUsed() || answered()) return;

		const incorrect = shuffledAnswers().filter(
			(a) => a !== q().correct_answer && !hiddenAnswers().includes(a),
		);

		const toHide = incorrect.sort(() => Math.random() - 0.5).slice(0, 2);
		setHiddenAnswers([...hiddenAnswers(), ...toHide]);
		setHintUsed(true);
	};

	return (
		<section class="quiz">
			<Show when={!loading() && q()} fallback={<div>Loading...</div>}>
				<h2>{decodeHtml(q().question)}</h2>

				<div class="answers">
					<For each={shuffledAnswers()}>
						{(ans) => {
							const isHidden = hiddenAnswers().includes(ans);

							const getClass = () => {
								if (hiddenAnswers().includes(ans)) return "answer hidden";
								if (answered()) {
									if (ans === q().correct_answer) return "answer correct";
									if (ans === selected()) return "answer incorrect";
								} else if (ans === selected()) {
									return "answer selected";
								}
								return "answer";
							};

							return (
								<button
									type="button"
									class={getClass()}
									onClick={() => handleSelect(ans)}
									disabled={answered() || isHidden}
								>
									{decodeHtml(ans)}
								</button>
							);
						}}
					</For>
				</div>

				<Show when={!hintUsed() && !answered()}>
					<button type="button" class="next-btn" onClick={useHint}>
						💡 Hint
					</button>
				</Show>

				<Show when={answered()}>
					<button type="button" class="next-btn" onClick={nextQuestion}>
						Next →
					</button>
				</Show>
			</Show>
		</section>
	);
}

// quizz-app-next/src/components/Quiz.tsx
"use client";

import axios from "axios";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import "../styles/Quiz.css";
import { decodeHtml } from "@/utils/decodeHtml";

interface QuizProps {
	category?: string;
	amount?: number;
	random?: boolean;
}

interface Question {
	question: string;
	correct_answer: string;
	incorrect_answers: string[];
}

export default function Quiz({
	category,
	amount = 10,
	random = false,
}: QuizProps) {
	const [questions, setQuestions] = useState<Question[]>([]);
	const [current, setCurrent] = useState(0);
	const [loading, setLoading] = useState(true);
	const [selected, setSelected] = useState<string | null>(null);
	const [answered, setAnswered] = useState(false);
	const [score, setScore] = useState(0);
	const router = useRouter();

	useEffect(() => {
		const fetchQuiz = async () => {
			setLoading(true);
			const catQuery = random ? "" : `&category=${category}`;
			const res = await axios.get(
				`https://opentdb.com/api.php?amount=${amount}&type=multiple${catQuery}`,
			);
			setQuestions(res.data.results);
			setLoading(false);
		};
		fetchQuiz();
	}, [category, random, amount]);

	const handleSelect = (answer: string) => {
		if (!answered) {
			setSelected(answer);
			setAnswered(true);
			if (answer === questions[current].correct_answer) {
				setScore((prev) => prev + 1);
			}
		}
	};

	const nextQuestion = () => {
		if (current + 1 >= questions.length) {
			router.push(`/score?score=${score}&total=${questions.length}`);
		} else {
			setCurrent((prev) => prev + 1);
			setSelected(null);
			setAnswered(false);
		}
	};

	if (loading) return <div className="quiz">Loading...</div>;

	const q = questions[current];
	const answers = [...q.incorrect_answers, q.correct_answer].sort(
		() => Math.random() - 0.5,
	);

	return (
		<section className="quiz">
			<h2>{decodeHtml(q.question)}</h2>
			<div className="answers">
				{answers.map((ans) => {
					let answerClass = "";
					if (answered) {
						if (ans === q.correct_answer) answerClass = "correct";
						else if (ans === selected) answerClass = "incorrect";
					} else if (selected === ans) {
						answerClass = "selected";
					}

					return (
						<button
							type="button"
							key={ans}
							className={`answer ${answerClass}`}
							onClick={() => handleSelect(ans)}
							disabled={answered}
						>
							{decodeHtml(ans)}
						</button>
					);
				})}
			</div>
			{answered && (
				<button type="button" className="next-btn" onClick={nextQuestion}>
					Next →
				</button>
			)}
		</section>
	);
}
